OzSapkaTShirtReposNew-master/OzSapkaTShirt/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OzSapkaTShirt.Data;
using OzSapkaTShirt.Models;
using System.Diagnostics;
using System.Security.Claims;

namespace OzSapkaTShirt.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationContext _context;

        public HomeController(ILogger<HomeController> logger, ApplicationContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index(string? id=null)
        {
                               

            return View(_context.Products.ToList());
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }



       


    }
}

OzSapkaTShirtReposNew-master/OzSapkaTShirt/Controllers/OrderProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OzSapkaTShirt.Data;
using OzSapkaTShirt.Models;

namespace OzSapkaTShirt.Controllers
{
    [Authorize]
    public class OrderProductsController : Controller
    {
        private readonly ApplicationContext _context;

        public OrderProductsController(ApplicationContext context)
        {
            _context = context;
        }
      

        public IActionResult UpDateBasket(long id, short quantity)
        {
            Order? order;
            OrderProduct? orderProduct;
            Product? product = _context.Products.Find(id);
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            order = _context.Orders.Where(o => o.UserId == userId && o.Status == 0).Include(o => o.OrderProducts).FirstOrDefault();
            if (order != null && order.OrderProducts != null)
            {
                foreach (var item in order.OrderProducts)
                {
                    if (item.Product == null)
                    {
                        item.Product = _context.Products.FirstOrDefault(q => q.Id == item.ProductId);
                    }
                }
            }

            if (order == null)
            {
                order = new Order();
                order.OrderDate = DateTime.Today;
                order.Status = 0;
                order.TotalPrice = 0;
                order.UserId = userId;
                order.OrderProducts = new List<OrderProduct>();
                _context.Add(order);
                _context.SaveChanges();
            }
            orderProduct = order.OrderProducts.Find(o => o.ProductId == id);
            if (orderProduct == null)
            {
                orderProduct = new OrderProduct();
                orderProduct.OrderId = order.Id;
                orderProduct.Price = product.Price;
                orderProduct.ProductId = id;
                orderProduct.Quantity = 1;
                orderProduct.Total = product.Price;
                order.OrderProducts.Add(orderProduct);
            }

            else
            {
                if (orderProduct.Quantity == quantity * -1)
                {
                    order.TotalPrice -= orderProduct.Price * orderProduct.Quantity;
                    order.OrderProducts.Remove(orderProduct);
                    _context.OrderProducts.Remove(orderProduct);
                    _context.SaveChanges();
                }
                orderProduct.Quantity += quantity;
                if (orderProduct.Quantity == 0)
                {

                    order.OrderProducts.Remove(orderProduct);
                    if (order.OrderProducts.Count == 0)
                    {
                        _context.Remove(order);
                        _context.SaveChanges();
                        HttpContext.Response.Cookies.Append("totalQuantity", order.OrderProducts.Sum(q => q.Quantity).ToString());
                        return PartialView("OrderDetailPartial", order);
                    }
                }
                else
                {
                    orderProduct.Total += product.Price * quantity;
                }
            }

            order.TotalPrice += product.Price * quantity;

            _context.Update(order);
            _context.SaveChanges();
            HttpContext.Response.Cookies.Append("totalQuantity", order.OrderProducts.Sum(q => q.Quantity).ToString());
            return PartialView("OrderDetailPartial", order);


        }




    }
}

OzSapkaTShirtReposNew-master/OzSapkaTShirt/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OzSapkaTShirt.Data;
using OzSapkaTShirt.Models;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Runtime.InteropServices;
using System.Drawing.Imaging;

namespace OzSapkaTShirt.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ApplicationContext _context;

        public ProductsController(ApplicationContext context)
        {
            _context = context;
        }

        // GET: Products
        public async Task<IActionResult> Index()
        {
            return _context.Products != null ?
                        View(await _context.Products.ToListAsync()) :
                        Problem("Entity set 'ApplicationContext.Product'  is null.");
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create

        // GET: Products/Edit/5

        // GET: Products/Delete/5
    }
}

OzSapkaTShirtReposNew-master/OzSapkaTShirt/Views/Home/Index.cshtml
@using System.Security.Claims

@model IEnumerable<OzSapkaTShirt.Models.Product>
@{
    //Layout = null; LAYOUT KALDIRMA İÇİN
    ViewData["Title"] = "Home Page";
}
<div class="text-center">Ürünler</div>

@foreach (var item in Model)
{
    <a class="card" style="width:102px;height:250px;display:inline-block;vertical-align:top" asp-controller="Products" asp-action="Details" asp-route-id="@item.Id">
        <span class="card-title">@item.Name.Trim()</span>
        @if(item.DBImage!=null)
        {
            <img class="card-img" src="data:image/png;base64,@Convert.ToBase64String(item.DBImage)" style="width:100px;display:block">
        }
       
        <span class="card-text">@item.Description.Trim()</span>
        <span class="card-text">@item.Price.ToString("F2")</span>
    </a>
    @if (User.FindFirstValue(ClaimTypes.NameIdentifier) != null)
    {

        <script>

            window.onload = function () {

                var quantity = readCookie('totalQuantity')
                if (quantity > 0) {
                    $('#basketCount').html(quantity);
                }

            };


          


            function AddToBasket(productId) {

               

                $.post("@Url.Action("UpDateBasket","OrderProducts")/" + productId+"?quantity=1");
                var quantity = readCookie('totalQuantity')
                if (quantity > 0) {
                    $('#basketCount').html(quantity)
                }

          }
        

        </script>
        <input type="button" value="SEPETE EKLE" onclick="AddToBasket(@item.Id.ToString())" />
    }
}